#!/bin/bash

echo "AMCertificationAuthority"

if [ ! -e ca.key ]; then
    echo "Создание приватного ключа сервера"
    openssl genrsa -out ca.key 4096

    echo "Создание сертификата сервера"
    openssl req -x509 -days 1825 -key ca.key -out ca.crt
fi

if [ ! -e ca.crt ]; then
    echo "Создание сертификата сервера"
    openssl req -x509 -days 1825 -key ca.key -out ca.crt
fi

if [ -z "$1" ]; then
    echo "    -n [domain], --new [domain]       Создание сертификата для домена"
    echo "    -u [domain], --update [domain]    Переиздание сертификата для домена"
    echo "    -h, --help                        Вывод справки"
fi

while [ -n "$1" ]
do
    case "$1" in
    -h | --help)
        echo "    -n [domain], --new [domain]       Создание сертификата для домена"
        echo "    -u [domain], --update [domain]    Переиздание сертификата для домена"
        echo "    -h, --help                        Вывод справки"
    ;;

    *)
        echo "Неизвестная опция"
    ;;

    esac

    shift
done
